# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/kane/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/kane

PRODUCT_COPY_FILES += \
    vendor/motorola/kane/proprietary/vendor/etc/sec_s3nrn81_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_s3nrn81_rfreg.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/fimc_is_rta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/himax-hix83112a-hx83112a-0C00-208-kane.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-hix83112a-hx83112a-0C00-208-kane.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/novatek_ts-nov36672a-NT36672A-190108-04-kane.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-nov36672a-NT36672A-190108-04-kane.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_0.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_1.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_2.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_3.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_4.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_5.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_6.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_7.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_8.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2p7sq.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2p7sq.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2t7sx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2t7sx.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2x5sp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2x5sp.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_5e9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_5e9.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_6b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_gm1sp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gm1sp.bin \
    vendor/motorola/kane/proprietary/vendor/lib/hw/camera.exynos9610.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.exynos9610.so \
    vendor/motorola/kane/proprietary/vendor/lib/hw/sensors.kane_sprout.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.kane_sprout.so \
    vendor/motorola/kane/proprietary/vendor/lib/libexynoscamera3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera3.so \
    vendor/motorola/kane/proprietary/vendor/lib/libril_sitril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril_sitril.so \
    vendor/motorola/kane/proprietary/vendor/lib/libsitril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsitril.so \
    vendor/motorola/kane/proprietary/vendor/lib/sensors.chub.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.chub.so \
    vendor/motorola/kane/proprietary/vendor/lib64/hw/camera.exynos9610.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/camera.exynos9610.so \
    vendor/motorola/kane/proprietary/vendor/lib64/hw/sensors.kane_sprout.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.kane_sprout.so \
    vendor/motorola/kane/proprietary/vendor/lib64/libexynoscamera3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libexynoscamera3.so \
    vendor/motorola/kane/proprietary/vendor/lib64/libril_sitril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril_sitril.so \
    vendor/motorola/kane/proprietary/vendor/lib64/libsitril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsitril.so \
    vendor/motorola/kane/proprietary/vendor/lib64/sensors.chub.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.chub.so
