# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm7325-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pstar nio,$(TARGET_DEVICE)),)

endif
