# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/obake/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/obake/proprietary/bin/adspd:system/bin/adspd \
    vendor/motorola/obake/proprietary/lib/libacdbdata.so:system/lib/libacdbdata.so \
    vendor/motorola/obake/proprietary/lib/libacdbdata_obakem.so:system/lib/libacdbdata_obakem.so \
    vendor/motorola/obake/proprietary/lib/libacdbdata_obake-maxx.so:system/lib/libacdbdata_obake-maxx.so \
    vendor/motorola/obake/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890.config:system/etc/firmware/tfa9890.config \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890.eq:system/etc/firmware/tfa9890.eq \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890.speaker:system/etc/firmware/tfa9890.speaker \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890_music_table.preset:system/etc/firmware/tfa9890_music_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890_n1b12.patch:system/etc/firmware/tfa9890_n1b12.patch \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890_n1c2.patch:system/etc/firmware/tfa9890_n1c2.patch \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890_ringtone_table.preset:system/etc/firmware/tfa9890_ringtone_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/tfa9890_voice_table.preset:system/etc/firmware/tfa9890_voice_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/VRGain.bin:system/etc/firmware/VRGain.bin \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890.config:system/etc/firmware/obakem/tfa9890.config \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890.eq:system/etc/firmware/obakem/tfa9890.eq \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890.speaker:system/etc/firmware/obakem/tfa9890.speaker \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890_music_table.preset:system/etc/firmware/obakem/tfa9890_music_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890_n1b12.patch:system/etc/firmware/obakem/tfa9890_n1b12.patch \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890_n1c2.patch:system/etc/firmware/obakem/tfa9890_n1c2.patch \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890_ringtone_table.preset:system/etc/firmware/obakem/tfa9890_ringtone_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/tfa9890_voice_table.preset:system/etc/firmware/obakem/tfa9890_voice_table.preset \
    vendor/motorola/obake/proprietary/etc/firmware/obakem/VRGain.bin:system/etc/firmware/obakem/VRGain.bin \
    vendor/motorola/obake/proprietary/etc/firmware/obake-maxx/VRGain.bin:system/etc/firmware/obake-maxx/VRGain.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obake.bin:system/etc/firmware/mspfirmware_obake.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obake_p0.bin:system/etc/firmware/mspfirmware_obake_p0.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obake_p1.bin:system/etc/firmware/mspfirmware_obake_p1.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obake_p2.bin:system/etc/firmware/mspfirmware_obake_p2.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obake.txt:system/etc/firmware/mspversion_obake.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obake_p0.txt:system/etc/firmware/mspversion_obake_p0.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obake_p1.txt:system/etc/firmware/mspversion_obake_p1.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obake_p2.txt:system/etc/firmware/mspversion_obake_p2.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obakem.bin:system/etc/firmware/mspfirmware_obakem.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obakem_p0.bin:system/etc/firmware/mspfirmware_obakem_p0.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obakem_p1.bin:system/etc/firmware/mspfirmware_obakem_p1.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspfirmware_obakem_p2.bin:system/etc/firmware/mspfirmware_obakem_p2.bin \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obakem.txt:system/etc/firmware/mspversion_obakem.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obakem_p0.txt:system/etc/firmware/mspversion_obakem_p0.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obakem_p1.txt:system/etc/firmware/mspversion_obakem_p1.txt \
    vendor/motorola/obake/proprietary/etc/firmware/mspversion_obakem_p2.txt:system/etc/firmware/mspversion_obakem_p2.txt \
    vendor/motorola/obake/proprietary/etc/firmware/synaptics-s3310b-13061200-16a405-obakem-p1.tdat:system/etc/firmware/synaptics-s3310b-13061200-16a405-obakem-p1.tdat \
    vendor/motorola/obake/proprietary/etc/firmware/synaptics-s3310b-13061201-16a405-obakem.tdat:system/etc/firmware/synaptics-s3310b-13061201-16a405-obakem.tdat \
    vendor/motorola/obake/proprietary/etc/firmware/synaptics-s3402-13042202-164656-obake.tdat:system/etc/firmware/synaptics-s3402-13042202-164656-obake.tdat \
    vendor/motorola/obake/proprietary/etc/firmware/synaptics-s3402b-13071701-16cadd-obake.tdat:system/etc/firmware/synaptics-s3402b-13071701-16cadd-obake.tdat
