# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/edison/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/edison/proprietary/bin/atrelay-ctrl.sh:system/bin/atrelay-ctrl.sh \
    vendor/motorola/edison/proprietary/bin/bridge_relay:system/bin/bridge_relay \
    vendor/motorola/edison/proprietary/bin/dbus-daemon:system/bin/dbus-daemon \
    vendor/motorola/edison/proprietary/bin/ecckeyd:system/bin/ecckeyd \
    vendor/motorola/edison/proprietary/bin/ee_driver:system/bin/ee_driver \
    vendor/motorola/edison/proprietary/bin/fmradioserver:system/bin/fmradioserver \
    vendor/motorola/edison/proprietary/bin/gkisystem:system/bin/gkisystem \
    vendor/motorola/edison/proprietary/bin/gps_driver:system/bin/gps_driver \
    vendor/motorola/edison/proprietary/bin/load_modules.sh:system/bin/load_modules.sh \
    vendor/motorola/edison/proprietary/bin/location:system/bin/location \
    vendor/motorola/edison/proprietary/bin/mfa:system/bin/mfa \
    vendor/motorola/edison/proprietary/bin/mfa_send:system/bin/mfa_send \
    vendor/motorola/edison/proprietary/bin/mid:system/bin/mid \
    vendor/motorola/edison/proprietary/bin/mld:system/bin/mld \
    vendor/motorola/edison/proprietary/bin/secclkd:system/bin/secclkd \
    vendor/motorola/edison/proprietary/bin/smu:system/bin/smu \
    vendor/motorola/edison/proprietary/bin/timedexec:system/bin/timedexec \
    vendor/motorola/edison/proprietary/bin/RxNDrv:system/bin/RxNDrv \
    vendor/motorola/edison/proprietary/bin/TIDrv:system/bin/TIDrv \
    vendor/motorola/edison/proprietary/etc/dbus.conf:system/etc/dbus.conf \
    vendor/motorola/edison/proprietary/etc/firmware/ap_bt_data.bin:system/etc/firmware/ap_bt_data.bin \
    vendor/motorola/edison/proprietary/etc/firmware/fm_rx_init_1283.2.bts:system/etc/firmware/fm_rx_init_1283.2.bts \
    vendor/motorola/edison/proprietary/etc/firmware/fmc_init_1283.2.bts:system/etc/firmware/fmc_init_1283.2.bts \
    vendor/motorola/edison/proprietary/etc/gps/RxN/MSLConfig.txt:system/etc/gps/RxN/MSLConfig.txt \
    vendor/motorola/edison/proprietary/etc/gps/RxN/license.key:system/etc/gps/RxN/license.key \
    vendor/motorola/edison/proprietary/etc/gps/RxN/security.key:system/etc/gps/RxN/security.key \
    vendor/motorola/edison/proprietary/etc/gps/ti/GPSCConfigFile.cfg:system/etc/gps/ti/GPSCConfigFile.cfg \
    vendor/motorola/edison/proprietary/etc/gps/ti/patch-X.0.ce:system/etc/gps/ti/patch-X.0.ce \
    vendor/motorola/edison/proprietary/etc/gps/ti/pathconfigfile.txt:system/etc/gps/ti/pathconfigfile.txt \
    vendor/motorola/edison/proprietary/etc/location.cfg:system/etc/location.cfg \
    vendor/motorola/edison/proprietary/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin:system/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin \
    vendor/motorola/edison/proprietary/etc/mfa.conf:system/etc/mfa.conf \
    vendor/motorola/edison/proprietary/etc/mid.conf:system/etc/mid.conf \
    vendor/motorola/edison/proprietary/lib/hw/gps.edison.so:system/lib/hw/gps.edison.so \
    vendor/motorola/edison/proprietary/lib/hw/sensors.edison.so:system/lib/hw/sensors.edison.so \
    vendor/motorola/edison/proprietary/lib/libFMRadio.so:system/lib/libFMRadio.so \
    vendor/motorola/edison/proprietary/lib/libadkutils.so:system/lib/libadkutils.so \
    vendor/motorola/edison/proprietary/lib/libamcm.so:system/lib/libamcm.so \
    vendor/motorola/edison/proprietary/lib/libapr-1.so:system/lib/libapr-1.so \
    vendor/motorola/edison/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/motorola/edison/proprietary/lib/libaudioril.so:system/lib/libaudioril.so \
    vendor/motorola/edison/proprietary/lib/libbabysit.so:system/lib/libbabysit.so \
    vendor/motorola/edison/proprietary/lib/libcap.so:system/lib/libcap.so \
    vendor/motorola/edison/proprietary/lib/libcdal.so:system/lib/libcdal.so \
    vendor/motorola/edison/proprietary/lib/libconfig.so:system/lib/libconfig.so \
    vendor/motorola/edison/proprietary/lib/libdataencrypt.so:system/lib/libdataencrypt.so \
    vendor/motorola/edison/proprietary/lib/libdbus.so:system/lib/libdbus.so \
    vendor/motorola/edison/proprietary/lib/libfm_stack.so:system/lib/libfm_stack.so \
    vendor/motorola/edison/proprietary/lib/libfmchr.so:system/lib/libfmchr.so \
    vendor/motorola/edison/proprietary/lib/libfmradio_jni.so:system/lib/libfmradio_jni.so \
    vendor/motorola/edison/proprietary/lib/libfmradioplayer.so:system/lib/libfmradioplayer.so \
    vendor/motorola/edison/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/motorola/edison/proprietary/lib/libgki.so:system/lib/libgki.so \
    vendor/motorola/edison/proprietary/lib/libgpsTI.so:system/lib/libgpsTI.so \
    vendor/motorola/edison/proprietary/lib/liblcdriver.so:system/lib/liblcdriver.so \
    vendor/motorola/edison/proprietary/lib/liblcm.so:system/lib/liblcm.so \
    vendor/motorola/edison/proprietary/lib/libmcphal.so:system/lib/libmcphal.so \
    vendor/motorola/edison/proprietary/lib/libmcphalgps.so:system/lib/libmcphalgps.so \
    vendor/motorola/edison/proprietary/lib/libmoliU5xx.so:system/lib/libmoliU5xx.so \
    vendor/motorola/edison/proprietary/lib/libmotodbgutils.so:system/lib/libmotodbgutils.so \
    vendor/motorola/edison/proprietary/lib/libmss.so:system/lib/libmss.so \
    vendor/motorola/edison/proprietary/lib/libmss.so.sig:system/lib/libmss.so.sig \
    vendor/motorola/edison/proprietary/lib/libpostcapimgproc_intf.so:system/lib/libpostcapimgproc_intf.so \
    vendor/motorola/edison/proprietary/lib/libtinyxml_stl.so:system/lib/libtinyxml_stl.so \
    vendor/motorola/edison/proprietary/lib/libu300-parser.so:system/lib/libu300-parser.so \
    vendor/motorola/edison/proprietary/lib/libu300-ril.so:system/lib/libu300-ril.so \
    vendor/motorola/edison/proprietary/lib/libusb.so:system/lib/libusb.so \
    vendor/motorola/edison/proprietary/usr/bin/gki_pd_notifier:system/usr/bin/gki_pd_notifier \
    vendor/motorola/edison/proprietary/usr/bin/panic_daemon:system/usr/bin/panic_daemon \
    vendor/motorola/edison/proprietary/usr/keylayout/atmxt-i2c.kl:system/usr/keylayout/atmxt-i2c.kl \
    vendor/motorola/edison/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/motorola/edison/proprietary/bin/ap_gain.bin:system/bin/ap_gain.bin \
    vendor/motorola/edison/proprietary/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    vendor/motorola/edison/proprietary/etc/firmware/ducati-m3.bin:system/etc/firmware/ducati-m3.bin \
    vendor/motorola/edison/proprietary/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
    vendor/motorola/edison/proprietary/lib/hw/audio.primary.omap4.so:system/lib/hw/audio.primary.omap4.so \
    vendor/motorola/edison/proprietary/lib/hw/audio.primary.ics.so:system/lib/hw/audio.primary.ics.so
