# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter msm8937,$(TARGET_BOARD_PLATFORM)),)

endif
