# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/xt925/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/xt925/proprietary/etc/firmware/melfas_45_7_15.fw:system/etc/firmware/melfas_45_7_15.fw \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b00:system/etc/firmware/dsps.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/motorola/xt925/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.b07:system/etc/firmware/modem.b07 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b00:system/etc/firmware/modem_fw.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b01:system/etc/firmware/modem_fw.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b02:system/etc/firmware/modem_fw.b02 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b03:system/etc/firmware/modem_fw.b03 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b04:system/etc/firmware/modem_fw.b04 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b05:system/etc/firmware/modem_fw.b05 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b06:system/etc/firmware/modem_fw.b06 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b07:system/etc/firmware/modem_fw.b07 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b08:system/etc/firmware/modem_fw.b08 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b09:system/etc/firmware/modem_fw.b09 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b10:system/etc/firmware/modem_fw.b10 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b13:system/etc/firmware/modem_fw.b13 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b14:system/etc/firmware/modem_fw.b14 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b21:system/etc/firmware/modem_fw.b21 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b22:system/etc/firmware/modem_fw.b22 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b23:system/etc/firmware/modem_fw.b23 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b25:system/etc/firmware/modem_fw.b25 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b26:system/etc/firmware/modem_fw.b26 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.b29:system/etc/firmware/modem_fw.b29 \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.flist:system/etc/firmware/modem_fw.flist \
    vendor/motorola/xt925/proprietary/etc/firmware/modem_fw.mdt:system/etc/firmware/modem_fw.mdt \
    vendor/motorola/xt925/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b00:system/etc/firmware/q6.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b01:system/etc/firmware/q6.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b03:system/etc/firmware/q6.b03 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b04:system/etc/firmware/q6.b04 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b05:system/etc/firmware/q6.b05 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.b06:system/etc/firmware/q6.b06 \
    vendor/motorola/xt925/proprietary/etc/firmware/q6.mdt:system/etc/firmware/q6.mdt \
    vendor/motorola/xt925/proprietary/etc/firmware/tzapps.b00:system/etc/firmware/tzapps.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/tzapps.b01:system/etc/firmware/tzapps.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/tzapps.b02:system/etc/firmware/tzapps.b02 \
    vendor/motorola/xt925/proprietary/etc/firmware/tzapps.b03:system/etc/firmware/tzapps.b03 \
    vendor/motorola/xt925/proprietary/etc/firmware/tzapps.mdt:system/etc/firmware/tzapps.mdt \
    vendor/motorola/xt925/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/motorola/xt925/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/motorola/xt925/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/motorola/xt925/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/motorola/xt925/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \
    vendor/motorola/xt925/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/motorola/xt925/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
