# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter foles parker def liber odessa minsk hanoip,$(TARGET_DEVICE)),)

endif
