# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/falcon/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/falcon/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/motorola/falcon/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/motorola/falcon/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/motorola/falcon/proprietary/lib/hw/sensors.msm8226.so:system/lib/hw/sensors.msm8226.so \
    vendor/motorola/falcon/proprietary/etc/firmware/aps-Falc-01300000-0130-falcon.tdat:system/etc/firmware/aps-Falc-01300000-0130-falcon.tdat \
    vendor/motorola/falcon/proprietary/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat:system/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat
