# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/channel/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/channel

PRODUCT_COPY_FILES += \
    vendor/motorola/channel/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-fpcservice:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint@2.1-fpcservice \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/att/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/att/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/bl_s/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/bl_s/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/common_s/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/common_s/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Bluetooth_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/General_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Global_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Handset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Hdmi_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Headset_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/acdbdata/na_tmo/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/na_tmo/Speaker_cal.acdb \
    vendor/motorola/channel/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/motorola/channel/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djn_hd_568.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djn_hd_568.xml \
    vendor/motorola/channel/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djn_hd_569.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djn_hd_569.xml \
    vendor/motorola/channel/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_dsbj_hd_570.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_dsbj_hd_570.xml \
    vendor/motorola/channel/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/ilitek-dsbj-ILI9881-0B-6C-channel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek-dsbj-ILI9881-0B-6C-channel.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/novatek_ts-djn-NT36525-181116-08-channel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-djn-NT36525-181116-08-channel.bin \
    vendor/motorola/channel/proprietary/vendor/firmware/novatek_ts-djn-NT36525B-190103-146-channel.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-djn-NT36525B-190103-146-channel.bin \
    vendor/motorola/channel/proprietary/vendor/lib/vendor.qti.hardware.fingerprint@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.fingerprint@1.0.so
