# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/everest/extract-files.sh - DO NOT EDIT


# All the blobs necessary for everest
PRODUCT_COPY_FILES += \
    vendor/motorola/everest/proprietary/akmd2:system/bin/akmd2 \
    vendor/motorola/everest/proprietary/batch:system/bin/batch \
    vendor/motorola/everest/proprietary/brcm_guci_drv:system/bin/brcm_guci_drv \
    vendor/motorola/everest/proprietary/bugtogo.sh:system/bin/bugtogo.sh \
    vendor/motorola/everest/proprietary/bypassfactory:system/bin/bypassfactory \
    vendor/motorola/everest/proprietary/chat-ril:system/bin/chat-ril \
    vendor/motorola/everest/proprietary/ftmipcd:system/bin/ftmipcd \
    vendor/motorola/everest/proprietary/location:system/bin/location \
    vendor/motorola/everest/proprietary/pppd:system/bin/pppd \
    vendor/motorola/everest/proprietary/pppd-ril:system/bin/pppd-ril \
    vendor/motorola/everest/proprietary/savebpver:system/bin/savebpver \
    vendor/motorola/everest/proprietary/tcmd:system/bin/tcmd \
    vendor/motorola/everest/proprietary/testpppd:system/bin/testpppd \
    vendor/motorola/everest/proprietary/vril-dump:system/bin/vril-dump \
    vendor/motorola/everest/proprietary/cpcap_gain.bin:system/etc/cpcap_gain.bin \
    vendor/motorola/everest/proprietary/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
    vendor/motorola/everest/proprietary/nvddk_audiofx_core.axf:system/etc/firmware/nvddk_audiofx_core.axf \
    vendor/motorola/everest/proprietary/nvddk_audiofx_transport.axf:system/etc/firmware/nvddk_audiofx_transport.axf \
    vendor/motorola/everest/proprietary/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/motorola/everest/proprietary/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/motorola/everest/proprietary/nvmm_audiomixer.axf:system/etc/firmware/nvmm_audiomixer.axf \
    vendor/motorola/everest/proprietary/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/motorola/everest/proprietary/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/motorola/everest/proprietary/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/motorola/everest/proprietary/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/motorola/everest/proprietary/nvmm_mp2dec.axf:system/etc/firmware/nvmm_mp2dec.axf \
    vendor/motorola/everest/proprietary/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/motorola/everest/proprietary/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/motorola/everest/proprietary/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/motorola/everest/proprietary/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/motorola/everest/proprietary/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
    vendor/motorola/everest/proprietary/nvmm_sw_mp3dec.axf:system/etc/firmware/nvmm_sw_mp3dec.axf \
    vendor/motorola/everest/proprietary/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/motorola/everest/proprietary/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/motorola/everest/proprietary/gps.conf:system/etc/gps.conf \
    vendor/motorola/everest/proprietary/gpsconfig.xml:system/etc/gpsconfig.xml \
    vendor/motorola/everest/proprietary/location.cfg:system/etc/location.cfg \
    vendor/motorola/everest/proprietary/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \
    vendor/motorola/everest/proprietary/tcmd_leds.cfg:system/etc/motorola/12m/tcmd_leds.cfg \
    vendor/motorola/everest/proprietary/pppd-ril.options:system/etc/ppp/peers/pppd-ril.options \
    vendor/motorola/everest/proprietary/suplcerts.bks:system/etc/security/suplcerts.bks \
    vendor/motorola/everest/proprietary/voip_aud_params.bin:system/etc/voip_aud_params.bin \
    vendor/motorola/everest/proprietary/bcm4329.cal:system/etc/wifi/bcm4329.cal \
    vendor/motorola/everest/proprietary/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
    vendor/motorola/everest/proprietary/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/motorola/everest/proprietary/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/motorola/everest/proprietary/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/motorola/everest/proprietary/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
    vendor/motorola/everest/proprietary/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/motorola/everest/proprietary/camera.stingray.so:system/lib/hw/camera.stingray.so \
    vendor/motorola/everest/proprietary/gps.stingray.so:system/lib/hw/gps.stingray.so \
    vendor/motorola/everest/proprietary/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/motorola/everest/proprietary/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/motorola/everest/proprietary/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/motorola/everest/proprietary/libdmengine.so:system/lib/libdmengine.so \
    vendor/motorola/everest/proprietary/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/motorola/everest/proprietary/libmoto_ecnswrapper.so:system/lib/libmoto_ecnswrapper.so \
    vendor/motorola/everest/proprietary/libmoto_ril.so:system/lib/libmoto_ril.so \
    vendor/motorola/everest/proprietary/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/motorola/everest/proprietary/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/motorola/everest/proprietary/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
    vendor/motorola/everest/proprietary/libnvdispatch_helper.so:system/lib/libnvdispatch_helper.so \
    vendor/motorola/everest/proprietary/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/motorola/everest/proprietary/libnvmm.so:system/lib/libnvmm.so \
    vendor/motorola/everest/proprietary/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/motorola/everest/proprietary/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/motorola/everest/proprietary/libnvmm_image.so:system/lib/libnvmm_image.so \
    vendor/motorola/everest/proprietary/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/motorola/everest/proprietary/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/motorola/everest/proprietary/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
    vendor/motorola/everest/proprietary/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/motorola/everest/proprietary/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/motorola/everest/proprietary/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/motorola/everest/proprietary/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/motorola/everest/proprietary/libnvomx.so:system/lib/libnvomx.so \
    vendor/motorola/everest/proprietary/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/motorola/everest/proprietary/libnvos.so:system/lib/libnvos.so \
    vendor/motorola/everest/proprietary/libnvrm.so:system/lib/libnvrm.so \
    vendor/motorola/everest/proprietary/libnvrm_channel.so:system/lib/libnvrm_channel.so \
    vendor/motorola/everest/proprietary/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/motorola/everest/proprietary/libnvsm.so:system/lib/libnvsm.so \
    vendor/motorola/everest/proprietary/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/motorola/everest/proprietary/libpkip.so:system/lib/libpkip.so \
    vendor/motorola/everest/proprietary/libpppd_plugin-ril.so:system/lib/libpppd_plugin-ril.so \
    vendor/motorola/everest/proprietary/libril.so:system/lib/libril.so \
    vendor/motorola/everest/proprietary/libril_rds.so:system/lib/libril_rds.so \
    vendor/motorola/everest/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/motorola/everest/proprietary/libtpa.so:system/lib/libtpa.so \
    vendor/motorola/everest/proprietary/libtpa_core.so:system/lib/libtpa_core.so \
    vendor/motorola/everest/proprietary/bootanimation-encrypted.zip:system/media/bootanimation-encrypted.zip \
    vendor/motorola/everest/proprietary/bootanimation.zip:system/media/bootanimation.zip \
    vendor/motorola/everest/proprietary/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/motorola/everest/proprietary/fw_bcm4329_mfg.bin:system/vendor/firmware/fw_bcm4329_mfg.bin

# All the apks necessary for everest
PRODUCT_PACKAGES += \
    AppDirectedSmsService \
    ConnMO \
    DMService \
    MotoLocationProxy \
    MotoModemUtil \
    StingrayProgramMenu \
    StingrayProgramMenuSystem

