# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/thea/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/thea/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/motorola/thea/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/motorola/thea/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/motorola/thea/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/motorola/thea/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/motorola/thea/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/motorola/thea/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/motorola/thea/proprietary/etc/firmware/synaptics-s2716-14061501-18a02a-thea.tdat:system/etc/firmware/synaptics-s2716-14061501-18a02a-thea.tdat \
    vendor/motorola/thea/proprietary/etc/firmware/synaptics-s3310b-14101602-1acbd5-thea.tdat:system/etc/firmware/synaptics-s3310b-14101602-1acbd5-thea.tdat \
    vendor/motorola/thea/proprietary/lib/hw/camera.vendor.msm8226.so:system/lib/hw/camera.vendor.msm8226.so \
    vendor/motorola/thea/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/motorola/thea/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/motorola/thea/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/motorola/thea/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so
