# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/xt926/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/xt926/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/motorola/xt926/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/motorola/xt926/proprietary/etc/firmware/apps.mbn:system/etc/firmware/apps.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.b01:system/etc/firmware/dsps.b01 \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.b02:system/etc/firmware/dsps.b02 \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.b03:system/etc/firmware/dsps.b03 \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.b04:system/etc/firmware/dsps.b04 \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.b05:system/etc/firmware/dsps.b05 \
    vendor/motorola/xt926/proprietary/etc/firmware/dsps.mdt:system/etc/firmware/dsps.mdt \
    vendor/motorola/xt926/proprietary/etc/firmware/fsg.mbn:system/etc/firmware/fsg.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/melfas_45_7_15.fw:system/etc/firmware/melfas_45_7_15.fw \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.b07:system/etc/firmware/modem.b07 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b00:system/etc/firmware/modem_fw.b00 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b01:system/etc/firmware/modem_fw.b01 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b02:system/etc/firmware/modem_fw.b02 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b03:system/etc/firmware/modem_fw.b03 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b04:system/etc/firmware/modem_fw.b04 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b05:system/etc/firmware/modem_fw.b05 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b08:system/etc/firmware/modem_fw.b08 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b09:system/etc/firmware/modem_fw.b09 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b10:system/etc/firmware/modem_fw.b10 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b13:system/etc/firmware/modem_fw.b13 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b14:system/etc/firmware/modem_fw.b14 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b23:system/etc/firmware/modem_fw.b23 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b26:system/etc/firmware/modem_fw.b26 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.b29:system/etc/firmware/modem_fw.b29 \
    vendor/motorola/xt926/proprietary/etc/firmware/modem_fw.mdt:system/etc/firmware/modem_fw.mdt \
    vendor/motorola/xt926/proprietary/etc/firmware/rpm.mbn:system/etc/firmware/rpm.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/sbl1.mbn:system/etc/firmware/sbl1.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/sbl2.mbn:system/etc/firmware/sbl2.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/sbl3.mbn:system/etc/firmware/sbl3.mbn \
    vendor/motorola/xt926/proprietary/etc/firmware/tz.mbn:system/etc/firmware/tz.mbn
