# Copyright (C) 2013 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/targa/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/targa/proprietary/lib/hw/gps.vendor.so:system/lib/hw/gps.vendor.so \
    vendor/motorola/targa/proprietary/lib/hw/sensors.targa.so:system/lib/hw/sensors.targa.so \
    vendor/motorola/targa/proprietary/lib/libnbgm_9.0.1.so:system/lib/libnbgm_9.0.1.so \
    vendor/motorola/targa/proprietary/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin:system/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin \
    vendor/motorola/targa/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/motorola/targa/proprietary/bin/ap_gain.bin:system/bin/ap_gain.bin \
    vendor/motorola/targa/proprietary/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    vendor/motorola/targa/proprietary/etc/firmware/ducati-m3.bin:system/etc/firmware/ducati-m3.bin \
    vendor/motorola/targa/proprietary/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
    vendor/motorola/targa/proprietary/lib/hw/audio.primary.omap4.so:system/lib/hw/audio.primary.omap4.so
