# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/exynos9610-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter kane troika,$(TARGET_DEVICE)),)

endif
