# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8916-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter harpia lux merlin osprey surnia,$(TARGET_DEVICE)),)

endif
