# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/clark/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

$(call inherit-product, vendor/motorola/clark/clark-vendor-blobs.mk)

# Prebuilt jars
PRODUCT_PACKAGES += \
    com.google.widevine.software.drm \
    com.motorola.motosignature \
    com.verizon.ims \
    org.simalliance.openmobileapi \
    qcnvitems \
    qcrilhook

# Prebuilt APKs
PRODUCT_PACKAGES += \
    DMConfigUpdateLight \
    HiddenMenuLight \
    ims \
    MotoSignatureApp

# Prebuilt privileged APKs
PRODUCT_PACKAGES += \
    atfwd \
    CNEService \
    ConnMO \
    CQATest \
    DCMO \
    DiagMon \
    DMService \
    LifetimeData \
    qcrilmsgtunnel \
    SprintDM

# Prebuilt libs needed for compilation
PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api

# Prebuilt vendor/libs needed for compilation
PRODUCT_PACKAGES += \
    libtime_genoff

