# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/omap4-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/omap4-common/proprietary/bin/extract-embedded-files:system/bin/extract-embedded-files \
    vendor/motorola/omap4-common/proprietary/bin/logcatd:system/bin/logcatd \
    vendor/motorola/omap4-common/proprietary/bin/logcatd-blan:system/bin/logcatd-blan \
    vendor/motorola/omap4-common/proprietary/bin/mm-wrigley-qc-dump.sh:system/bin/mm-wrigley-qc-dump.sh \
    vendor/motorola/omap4-common/proprietary/bin/oem-iptables-init.sh:system/bin/oem-iptables-init.sh \
    vendor/motorola/omap4-common/proprietary/bin/vril-dump:system/bin/vril-dump \
    vendor/motorola/omap4-common/proprietary/bin/wrigley-diag.sh:system/bin/wrigley-diag.sh \
    vendor/motorola/omap4-common/proprietary/bin/wrigley-dump.sh:system/bin/wrigley-dump.sh \
    vendor/motorola/omap4-common/proprietary/bin/wrigley-fetch-mpr.sh:system/bin/wrigley-fetch-mpr.sh \
    vendor/motorola/omap4-common/proprietary/bin/wrigley-iptables.sh:system/bin/wrigley-iptables.sh \
    vendor/motorola/omap4-common/proprietary/lib/libb64.so:system/lib/libb64.so \
    vendor/motorola/omap4-common/proprietary/lib/libbabysit.so:system/lib/libbabysit.so \
    vendor/motorola/omap4-common/proprietary/lib/libmotdb.so:system/lib/libmotdb.so \
    vendor/motorola/omap4-common/proprietary/lib/lib-mot-lte-ril.so:system/lib/lib-mot-lte-ril.so \
    vendor/motorola/omap4-common/proprietary/lib/libmoto_mdmctrl.so:system/lib/libmoto_mdmctrl.so \
    vendor/motorola/omap4-common/proprietary/lib/libmoto_nwif_ril.so:system/lib/libmoto_nwif_ril.so \
    vendor/motorola/omap4-common/proprietary/lib/libmoto_qmi_ril.so:system/lib/libmoto_qmi_ril.so \
    vendor/motorola/omap4-common/proprietary/lib/libmoto_ril.so:system/lib/libmoto_ril.so \
    vendor/motorola/omap4-common/proprietary/lib/librds_util.so:system/lib/librds_util.so \
    vendor/motorola/omap4-common/proprietary/lib/libril_rds.so:system/lib/libril_rds.so \
    vendor/motorola/omap4-common/proprietary/lib/moto-ril-multimode.so:system/lib/moto-ril-multimode.so \
    vendor/motorola/omap4-common/proprietary/lib/libims_client_jni.so:system/lib/libims_client_jni.so \
    vendor/motorola/omap4-common/proprietary/lib/libmotricity.so:system/lib/libmotricity.so \
    vendor/motorola/omap4-common/proprietary/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml:system/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml \
    vendor/motorola/omap4-common/proprietary/etc/permissions/com.verizon.hardware.telephony.lte.xml:system/etc/permissions/com.verizon.hardware.telephony.lte.xml \
    vendor/motorola/omap4-common/proprietary/etc/permissions/com.vzw.vzwapnlib.xml:system/etc/permissions/com.vzw.vzwapnlib.xml
