# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/omap4-common/setup-makefiles.sh

PRODUCT_PROPERTY_OVERRIDES += \
    drm.service.enabled=true

PRODUCT_COPY_FILES += \
    vendor/motorola/omap4-common/proprietary/bin/batch:system/bin/batch \
    vendor/motorola/omap4-common/proprietary/bin/battd:system/bin/battd \
    vendor/motorola/omap4-common/proprietary/bin/dbvc_atvc_property_set:system/bin/dbvc_atvc_property_set \
    vendor/motorola/omap4-common/proprietary/bin/dumpe2fs:system/bin/dumpe2fs \
    vendor/motorola/omap4-common/proprietary/bin/enc_mgt_tool:system/bin/enc_mgt_tool \
    vendor/motorola/omap4-common/proprietary/bin/fips_loader:system/bin/fips_loader \
    vendor/motorola/omap4-common/proprietary/bin/ftmipcd:system/bin/ftmipcd \
    vendor/motorola/omap4-common/proprietary/bin/libthermal-manager.cfg:system/bin/libthermal-manager.cfg \
    vendor/motorola/omap4-common/proprietary/bin/mount_ext3.sh:system/bin/mount_ext3.sh \
    vendor/motorola/omap4-common/proprietary/bin/startup_smc.sh:system/bin/startup_smc.sh \
    vendor/motorola/omap4-common/proprietary/bin/thermaldaemon:system/bin/thermaldaemon \
    vendor/motorola/omap4-common/proprietary/bin/tty2ttyd:system/bin/tty2ttyd \
    vendor/motorola/omap4-common/proprietary/bin/whisperd:system/bin/whisperd \
    vendor/motorola/omap4-common/proprietary/etc/ecryptfs.tab:system/etc/ecryptfs.tab \
    vendor/motorola/omap4-common/proprietary/etc/encrypt.tab:system/etc/encrypt.tab \
    vendor/motorola/omap4-common/proprietary/etc/smc_android_cfg.ini:system/etc/smc_android_cfg.ini \
    vendor/motorola/omap4-common/proprietary/etc/smc_pa.ift:system/etc/smc_pa.ift \
    vendor/motorola/omap4-common/proprietary/etc/smc_pa_pk_4_8Mb_ipa.bin:system/etc/smc_pa_pk_4_8Mb_ipa.bin \
    vendor/motorola/omap4-common/proprietary/etc/smc_pa_pk_4_ipa.bin:system/etc/smc_pa_pk_4_ipa.bin \
    vendor/motorola/omap4-common/proprietary/etc/firmware/ap_bt_data.bin:system/etc/firmware/ap_bt_data.bin \
    vendor/motorola/omap4-common/proprietary/usr/idc/Motorola_Mobility_Motorola_HD_Dock.idc:system/usr/idc/Motorola_Mobility_Motorola_HD_Dock.idc \
    vendor/motorola/omap4-common/proprietary/usr/keylayout/cpcap-key.kl:system/usr/keylayout/cpcap-key.kl \
    vendor/motorola/omap4-common/proprietary/lib/hw/alsa.omap4.so:system/lib/hw/alsa.omap4.so \
    vendor/motorola/omap4-common/proprietary/lib/libaudio_ext.so:system/lib/libaudio_ext.so \
    vendor/motorola/omap4-common/proprietary/lib/libbattd.so:system/lib/libbattd.so \
    vendor/motorola/omap4-common/proprietary/lib/libdataencrypt_openssl.so:system/lib/libdataencrypt_openssl.so \
    vendor/motorola/omap4-common/proprietary/lib/libdataencrypt_tpa.so:system/lib/libdataencrypt_tpa.so \
    vendor/motorola/omap4-common/proprietary/lib/libdataencrypt_utils.so:system/lib/libdataencrypt_utils.so \
    vendor/motorola/omap4-common/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/motorola/omap4-common/proprietary/lib/libhdcp.so:system/lib/libhdcp.so \
    vendor/motorola/omap4-common/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/motorola/omap4-common/proprietary/lib/libmot_atcmd.so:system/lib/libmot_atcmd.so \
    vendor/motorola/omap4-common/proprietary/lib/libmoto_netutil.so:system/lib/libmoto_netutil.so \
    vendor/motorola/omap4-common/proprietary/lib/libnmea.so:system/lib/libnmea.so \
    vendor/motorola/omap4-common/proprietary/lib/libopenssl-smime.so:system/lib/libopenssl-smime.so \
    vendor/motorola/omap4-common/proprietary/lib/libOMX.ITTIAM.AAC.encode.so:system/lib/libOMX.ITTIAM.AAC.encode.so \
    vendor/motorola/omap4-common/proprietary/lib/libpkip.so:system/lib/libpkip.so \
    vendor/motorola/omap4-common/proprietary/lib/libpppd_plugin-ril.so:system/lib/libpppd_plugin-ril.so \
    vendor/motorola/omap4-common/proprietary/lib/libsmapi.so:system/lib/libsmapi.so \
    vendor/motorola/omap4-common/proprietary/lib/libthermal_config.so:system/lib/libthermal_config.so \
    vendor/motorola/omap4-common/proprietary/lib/libthermal_manager.so:system/lib/libthermal_manager.so \
    vendor/motorola/omap4-common/proprietary/lib/libtpa.so:system/lib/libtpa.so \
    vendor/motorola/omap4-common/proprietary/lib/libtpa_core.so:system/lib/libtpa_core.so \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/SEN2.cfg:system/etc/omapcam/SEN2.cfg \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/SEN2_EE.cfg:system/etc/omapcam/SEN2_EE.cfg \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_cal/cid1039_ov8820_alg_3a_ae_supp3_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_alg_3a_ae_supp3_dcc.bin \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_cal/cid1039_ov8820_isif_clamp_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_isif_clamp_dcc.bin \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_cal/cid1039_ov8820_lsc_interp.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_lsc_interp.bin \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_ee/cid1039_ov8820_ducati_gamma.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_gamma.bin \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_ee/cid1039_ov8820_ipipe_ee_dcc.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ipipe_ee_dcc.bin \
    vendor/motorola/omap4-common/proprietary/etc/omapcam/module1_ee/cid1039_ov8820_ducati_nsf_ldc.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_nsf_ldc.bin \
    vendor/motorola/omap4-common/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/motorola/omap4-common/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/motorola/omap4-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/motorola/omap4-common/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/motorola/omap4-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/motorola/omap4-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
