# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/motus/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/motorola/motus/proprietary/libloc_api.so:obj/lib/libloc_api.so \
    vendor/motorola/motus/proprietary/libril-qc-1.so:obj/lib/libril-qc-1.so

# All the blobs necessary for motus
PRODUCT_COPY_FILES += \
    vendor/motorola/motus/proprietary/akmd2:system/bin/akmd2 \
    vendor/motorola/motus/proprietary/touchpad:system/bin/touchpad \
    vendor/motorola/motus/proprietary/minipadut:system/bin/minipadut \
    vendor/motorola/motus/proprietary/qmuxd:system/bin/qmuxd \
    vendor/motorola/motus/proprietary/fuel_gauge:system/bin/fuel_gauge \
    vendor/motorola/motus/proprietary/port_bridge:system/bin/port_bridge \
    vendor/motorola/motus/proprietary/tcmd_engine:system/bin/tcmd_engine \
    vendor/motorola/motus/proprietary/tcmd_sql:system/bin/tcmd_sql \
    vendor/motorola/motus/proprietary/bt_downloader:system/bin/bt_downloader \
    vendor/motorola/motus/proprietary/bt_init:system/bin/bt_init \
    vendor/motorola/motus/proprietary/bt_init.config:system/etc/bt_init.config \
    vendor/motorola/motus/proprietary/akmd_set.cfg:system/etc/akm/akmd_set.cfg \
    vendor/motorola/motus/proprietary/0006.dffs:system/etc/fuel_gauge/0006.dffs \
    vendor/motorola/motus/proprietary/0301.bqfs:system/etc/fuel_gauge/0301.bqfs \
    vendor/motorola/motus/proprietary/minipad.cfg:system/etc/minipad/104/minipad.cfg \
    vendor/motorola/motus/proprietary/minipad.enc:system/etc/minipad/104/minipad.enc \
    vendor/motorola/motus/proprietary/saveconfig.cfg:system/etc/minipad/104/saveconfig.cfg \
    vendor/motorola/motus/proprietary/touchpad.cfg:system/etc/touchpad/50/touchpad.cfg \
    vendor/motorola/motus/proprietary/touchpad.enc:system/etc/touchpad/50/touchpad.enc \
    vendor/motorola/motus/proprietary/saveconfig.cfg:system/etc/touchpad/50/saveconfig.cfg \
    vendor/motorola/motus/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    vendor/motorola/motus/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    vendor/motorola/motus/proprietary/BCM4325D1_004.002.004.0218.0225.hcd:system/etc/BCM4325D1_004.002.004.0218.0225.hcd \
    vendor/motorola/motus/proprietary/sdio-g-cdc-reclaim-wme.bin:system/etc/wifi/sdio-g-cdc-reclaim-wme.bin \
    vendor/motorola/motus/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
    vendor/motorola/motus/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/motorola/motus/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/motorola/motus/proprietary/libril-moto-umts-1.so:system/lib/libril-moto-umts-1.so \
    vendor/motorola/motus/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/motorola/motus/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/motorola/motus/proprietary/libnv.so:system/lib/libnv.so \
    vendor/motorola/motus/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/motorola/motus/proprietary/libcm.so:system/lib/libcm.so \
    vendor/motorola/motus/proprietary/libdss.so:system/lib/libdss.so \
    vendor/motorola/motus/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/motorola/motus/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/motorola/motus/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/motorola/motus/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/motorola/motus/proprietary/libwms.so:system/lib/libwms.so \
    vendor/motorola/motus/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/motorola/motus/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/motorola/motus/proprietary/libsnd.so:system/lib/libsnd.so \
    vendor/motorola/motus/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/motorola/motus/proprietary/libmmcamera.so:system/lib/libmmcamera.so \
    vendor/motorola/motus/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/motorola/motus/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/motorola/motus/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/motorola/motus/proprietary/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/motorola/motus/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/motorola/motus/proprietary/libvideotrimer.so:system/lib/libvideotrimer.so \
    vendor/motorola/motus/proprietary/libmm-qcamera-tgt.so:system/lib/libmm-qcamera-tgt.so \
    vendor/motorola/motus/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/motorola/motus/proprietary/libhpprop.so:system/lib/libhpprop.so \
    vendor/motorola/motus/proprietary/libspeech.so:system/lib/libspeech.so \
    vendor/motorola/motus/proprietary/nvram.txt:system/etc/wifi/nvram.txt \
    vendor/motorola/motus/proprietary/charge_only_mode:root/sbin/charge_only_mode

