# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/river/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_boe_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_boe_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_h_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_h_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_n_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_n_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_haptic.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Argo_Navis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Argo_Navis.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Attentive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Attentive.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Awake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Awake.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Bird_Loop.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Bird_Loop.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Brilliant_Times.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Brilliant_Times.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Chimey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Chimey_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Complex.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Complex.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Crazy_Dream.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Crazy_Dream.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Curve_Ball_Blend.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Curve_Ball_Blend.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Digital_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Digital_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Electrovision.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Electrovision.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Ether_Shake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Ether_Shake.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Fateful_Words.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Fateful_Words.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Flutey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Flutey_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Future_Funk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Future_Funk.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Future_Hi_Tech.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Future_Hi_Tech.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Girtab.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Girtab.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hello.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hello.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hexagon.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hexagon.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hydra.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hydra.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Insert_Coin.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Insert_Coin.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Jumping_Dots.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Jumping_Dots.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Keys.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Keys.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Loopy.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Loopy.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Loopy_Lounge.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Loopy_Lounge.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Modular.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Modular.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Momentum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Momentum.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Morning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Morning.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Moto.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Moto.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Natural.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Natural.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_New_Player.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_New_Player.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Onward.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Onward.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Organ_Dub.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Organ_Dub.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Overclocked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Overclocked.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Pegasus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Pegasus.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Pyxis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Pyxis.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Regrade.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Regrade.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Scarabaeus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Scarabaeus.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Sceptrum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Sceptrum.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Simple.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Simple.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Solarium.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Solarium.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Sparse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Sparse.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Terrabytes.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Terrabytes.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx0.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx1.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx2.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx3.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx4.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx5.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx6.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx7.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali-na.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali-na.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-diag.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-diag.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-na.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-na.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/himax-boe-hx83112a-0a05-208-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-boe-hx83112a-0a05-208-river.bin \
    vendor/motorola/river/proprietary/vendor/firmware/himax-boe-hx83112a-river.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-boe-hx83112a-river.csv \
    vendor/motorola/river/proprietary/vendor/firmware/himax-tianmah-hx83112a-0500-208-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-tianmah-hx83112a-0500-208-river.bin \
    vendor/motorola/river/proprietary/vendor/firmware/himax-tianmah-hx83112a-river.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-tianmah-hx83112a-river.csv \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp1-ultrasound.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp1-ultrasound.bin \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp1-ultrasound.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp1-ultrasound.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp2-aov-frontend.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-frontend.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp2-aov-vrgain.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-vrgain.bin \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp3-aov-control.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp3-aov-control.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/novatek_ts-tianman-NT36672A-181127-0b-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-tianman-NT36672A-181127-0b-river.bin
