# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/hannah-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter ahannah hannah rhannah,$(TARGET_DEVICE)),)

endif
