# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/ghost/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/ghost/proprietary/bin/adspd:system/bin/adspd \
    vendor/motorola/ghost/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890.config:system/etc/firmware/tfa9890.config \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890.eq:system/etc/firmware/tfa9890.eq \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890.speaker:system/etc/firmware/tfa9890.speaker \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890_music_table.preset:system/etc/firmware/tfa9890_music_table.preset \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890_n1b12.patch:system/etc/firmware/tfa9890_n1b12.patch \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890_n1c2.patch:system/etc/firmware/tfa9890_n1c2.patch \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890_ringtone_table.preset:system/etc/firmware/tfa9890_ringtone_table.preset \
    vendor/motorola/ghost/proprietary/etc/firmware/tfa9890_voice_table.preset:system/etc/firmware/tfa9890_voice_table.preset \
    vendor/motorola/ghost/proprietary/etc/firmware/VRGain.bin:system/etc/firmware/VRGain.bin \
    vendor/motorola/ghost/proprietary/etc/firmware/mspfirmware.bin:system/etc/firmware/mspfirmware.bin \
    vendor/motorola/ghost/proprietary/etc/firmware/mspfirmware_p0.bin:system/etc/firmware/mspfirmware_p0.bin \
    vendor/motorola/ghost/proprietary/etc/firmware/mspfirmware_p1.bin:system/etc/firmware/mspfirmware_p1.bin \
    vendor/motorola/ghost/proprietary/etc/firmware/mspfirmware_p2.bin:system/etc/firmware/mspfirmware_p2.bin \
    vendor/motorola/ghost/proprietary/etc/firmware/mspversion.txt:system/etc/firmware/mspversion.txt \
    vendor/motorola/ghost/proprietary/etc/firmware/mspversion_p0.txt:system/etc/firmware/mspversion_p0.txt \
    vendor/motorola/ghost/proprietary/etc/firmware/mspversion_p1.txt:system/etc/firmware/mspversion_p1.txt \
    vendor/motorola/ghost/proprietary/etc/firmware/mspversion_p2.txt:system/etc/firmware/mspversion_p2.txt \
    vendor/motorola/ghost/proprietary/etc/firmware/synaptics-s3402-13040101-164656-ghost.tdat:system/etc/firmware/synaptics-s3402-13040101-164656-ghost.tdat \
    vendor/motorola/ghost/proprietary/etc/firmware/synaptics-s3402-13040101-164656-ghost-p1a.tdat:system/etc/firmware/synaptics-s3402-13040101-164656-ghost-p1a.tdat \
    vendor/motorola/ghost/proprietary/etc/firmware/synaptics-s3402b-13050201-167746-ghost.tdat:system/etc/firmware/synaptics-s3402b-13050201-167746-ghost.tdat
