# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/ghost/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/ghost/proprietary/xt1080/bin/ap_gain.bin:system/xt1080/bin/ap_gain.bin \
    vendor/motorola/ghost/proprietary/xt1080/bin/ap_gain_mmul.bin:system/xt1080/bin/ap_gain_mmul.bin \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/VRGain.bin:system/xt1080/etc/firmware/VRGain.bin \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890.config:system/xt1080/etc/firmware/tfa9890.config \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890.speaker:system/xt1080/etc/firmware/tfa9890.speaker \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890.eq:system/xt1080/etc/firmware/tfa9890.eq \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890_music_table.preset:system/xt1080/etc/firmware/tfa9890_music_table.preset \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890_n1b12.patch:system/xt1080/etc/firmware/tfa9890_n1b12.patch \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890_n1c2.patch:system/xt1080/etc/firmware/tfa9890_n1c2.patch \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890_ringtone_table.preset:system/xt1080/etc/firmware/tfa9890_ringtone_table.preset \
    vendor/motorola/ghost/proprietary/xt1080/etc/firmware/tfa9890_voice_table.preset:system/xt1080/etc/firmware/tfa9890_voice_table.preset \
    vendor/motorola/ghost/proprietary/xt1080/lib/libacdbdata.so:system/xt1080/lib/libacdbdata.so \
    vendor/motorola/ghost/proprietary/xt1080/lib/libaudcal.so:system/xt1080/lib/libaudcal.so
