# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/harpia/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/harpia

PRODUCT_COPY_FILES += \
    vendor/motorola/harpia/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/harpia/proprietary/vendor/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/motorola/harpia/proprietary/vendor/lib/hw/camera.vendor.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.msm8916.so \
    vendor/motorola/harpia/proprietary/vendor/lib/hw/sensors.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.msm8916.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_f8v03t_dw9718s.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_f8v03t_dw9718s.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_f8v03t_dw9718s_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_f8v03t_dw9718s_camcorder.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_f8v03t_dw9718s_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_f8v03t_dw9718s_camera.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_l8865aa0_dw9718s.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_l8865aa0_dw9718s.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_l8865aa0_dw9718s_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_l8865aa0_dw9718s_camcorder.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libactuator_l8865aa0_dw9718s_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_l8865aa0_dw9718s_camera.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libadvalgcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadvalgcore.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_beautyshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libcamerabgproc-jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamerabgproc-jni.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libcamerabgprocservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamerabgprocservice.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_common.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_default_video.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_hfr_120fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_hfr_60fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_hfr_90fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_liveshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_common.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_default_video.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_liveshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_preview.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_snapshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_video_hd.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_ofilm_l5695f40_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_ofilm_l5695f40_zsl.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_preview.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_snapshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_video_hd.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov5695_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5695_zsl.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_common.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_default_video.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_hfr_120fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_hfr_60fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_hfr_90fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_liveshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_preview.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_snapshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_video_hd.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_f8v03t_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_f8v03t_zsl.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_common.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_default_video.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_hfr_120fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_hfr_60fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_hfr_90fps.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_liveshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_preview.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_snapshot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_video_hd.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libchromatix_ov8865_l8865aa0_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_l8865aa0_zsl.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libjscore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjscore.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libjustshoot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjustshoot.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qcamera.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_interface.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_lux_standardization.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_lux_standardization.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_ov5695.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5695.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_ov8865_f8v03t.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov8865_f8v03t.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_sunny_d5v16b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_d5v16b_eeprom.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_sunny_f8v03t_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_f8v03t_eeprom.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmot-qc-fd-offline.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmot-qc-fd-offline.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmotimager_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmotimager_utils.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmotocalibration.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmotocalibration.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase.so \
    vendor/motorola/harpia/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    vendor/motorola/harpia/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so
