# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/moto_msm8960dt/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS += vendor/motorola/moto_msm8960dt/overlay

$(call inherit-product, vendor/motorola/moto_msm8960dt/moto_msm8960dt-vendor-blobs.mk)
$(call inherit-product, vendor/motorola/qcom-common/qcom-common-vendor.mk)
PRODUCT_PACKAGES += qcnvitems
PRODUCT_PACKAGES += qcrilhook
