# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/msm8960-common/setup-makefiles.sh

LOCAL_PATH:=vendor/motorola/msm8960-common/X

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	$(LOCAL_PATH)/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	$(LOCAL_PATH)/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	$(LOCAL_PATH)/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	$(LOCAL_PATH)/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	$(LOCAL_PATH)/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	$(LOCAL_PATH)/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
	$(LOCAL_PATH)/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
	$(LOCAL_PATH)/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
	$(LOCAL_PATH)/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
	$(LOCAL_PATH)/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
	$(LOCAL_PATH)/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
	$(LOCAL_PATH)/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
	$(LOCAL_PATH)/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
	$(LOCAL_PATH)/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	$(LOCAL_PATH)/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	$(LOCAL_PATH)/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	$(LOCAL_PATH)/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	$(LOCAL_PATH)/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
	$(LOCAL_PATH)/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	$(LOCAL_PATH)/lib/libacdbloader.so:system/lib/libacdbloader.so \
	$(LOCAL_PATH)/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
	$(LOCAL_PATH)/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
	$(LOCAL_PATH)/lib/libC2D2.so:system/lib/libC2D2.so \
	$(LOCAL_PATH)/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
	$(LOCAL_PATH)/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
	$(LOCAL_PATH)/lib/libgeofence.so:system/lib/libgeofence.so \
	$(LOCAL_PATH)/lib/libgsl.so:system/lib/libgsl.so \
	$(LOCAL_PATH)/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
	$(LOCAL_PATH)/lib/libmmosal.so:system/lib/libmmosal.so \
	$(LOCAL_PATH)/lib/libmmparser.so:system/lib/libmmparser.so \
	$(LOCAL_PATH)/lib/libOpenCL.so:system/lib/libOpenCL.so \
	$(LOCAL_PATH)/lib/libOpenVG.so:system/lib/libOpenVG.so \
	$(LOCAL_PATH)/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
	$(LOCAL_PATH)/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so
