# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/msm8960-common/setup-makefiles.sh

LOCAL_PATH:=vendor/motorola/msm8960-common/jf

# Libs from jf (Samsung Galaxy S4)
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    $(LOCAL_PATH)/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    $(LOCAL_PATH)/lib/libC2D2.so:system/lib/libC2D2.so \
    $(LOCAL_PATH)/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
    $(LOCAL_PATH)/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    $(LOCAL_PATH)/lib/libmmosal.so:system/lib/libmmosal.so \
    $(LOCAL_PATH)/lib/libmmparser.so:system/lib/libmmparser.so
