# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/qcom-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/qcom-common/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/motorola/qcom-common/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/motorola/qcom-common/proprietary/bin/dbvc_atvc_property_set:system/bin/dbvc_atvc_property_set \
    vendor/motorola/qcom-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/motorola/qcom-common/proprietary/bin/ftmipcd:system/bin/ftmipcd \
    vendor/motorola/qcom-common/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/motorola/qcom-common/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/motorola/qcom-common/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/motorola/qcom-common/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/motorola/qcom-common/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/motorola/qcom-common/proprietary/bin/radish:system/bin/radish \
    vendor/motorola/qcom-common/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/motorola/qcom-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/motorola/qcom-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/motorola/qcom-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/motorola/qcom-common/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/motorola/qcom-common/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/motorola/qcom-common/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/motorola/qcom-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/motorola/qcom-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/motorola/qcom-common/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/motorola/qcom-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/motorola/qcom-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/motorola/qcom-common/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/motorola/qcom-common/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/motorola/qcom-common/proprietary/lib/libxt_v02.so:system/lib/libxt_v02.so \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/motorola/qcom-common/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/motorola/qcom-common/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/motorola/qcom-common/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/motorola/qcom-common/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/motorola/qcom-common/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/motorola/qcom-common/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/motorola/qcom-common/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/motorola/qcom-common/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/motorola/qcom-common/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/motorola/qcom-common/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/motorola/qcom-common/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/motorola/qcom-common/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/motorola/qcom-common/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/motorola/qcom-common/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/motorola/qcom-common/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/motorola/qcom-common/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/motorola/qcom-common/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/motorola/qcom-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/motorola/qcom-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/motorola/qcom-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/motorola/qcom-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so
