# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/vanquish/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/vanquish/proprietary/etc/firmware/atmxt-r1.tdat:system/etc/firmware/atmxt-r1.tdat \
    vendor/motorola/vanquish/proprietary/etc/firmware/atmxt-r2.tdat:system/etc/firmware/atmxt-r2.tdat \
    vendor/motorola/vanquish/proprietary/etc/firmware/melfas_45_7_15.fw:system/etc/firmware/melfas_45_7_15.fw \
    vendor/motorola/vanquish/proprietary/xt897/lib/libaudcal.so:system/xt897/lib/libaudcal.so \
    vendor/motorola/vanquish/proprietary/xt897/etc/firmware/atmxt-r2.tdat:system/xt897/etc/firmware/atmxt-r2.tdat \
    vendor/motorola/vanquish/proprietary/xt901/lib/libqmiservices.so:system/xt901/lib/libqmiservices.so \
    vendor/motorola/vanquish/proprietary/xt901/lib/libril-qc-qmi-1.so:system/xt901/lib/libril-qc-qmi-1.so \
    vendor/motorola/vanquish/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/motorola/vanquish/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
