# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/nio/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/nio

PRODUCT_COPY_FILES += \
    vendor/motorola/nio/proprietary/vendor/etc/thermal-engine-nio.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-nio.conf
